### ISSUE TITLE
AWS internal LoadBalancer IP's not resolved

### ISSUE THREAD

**Issue by frezbo** [NoExitTV/pi-dns#9]
When using Pi-DNS normal or DoH AWS internal load balancer IP's are not resolved.

*Normal DNS*

**Using CloudFlare**

```bash
$ dig @1.1.1.1 internal-af90b8a66a8624061b5e32cc076dd867-1295241024.us-east-1.elb.amazonaws.com

; <<>> DiG 9.10.6 <<>> @1.1.1.1 internal-af90b8a66a8624061b5e32cc076dd867-1295241024.us-east-1.elb.amazonaws.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1849
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;internal-af90b8a66a8624061b5e32cc076dd867-1295241024.us-east-1.elb.amazonaws.com. IN A

;; ANSWER SECTION:
internal-af90b8a66a8624061b5e32cc076dd867-1295241024.us-east-1.elb.amazonaws.com. 60 IN	A 10.1.28.204

;; Query time: 384 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Tue Aug 11 22:31:52 IST 2020
;; MSG SIZE  rcvd: 205
```

**Using Pi-DNS**

```bash
$ dig @185.213.26.187 internal-af90b8a66a8624061b5e32cc076dd867-1295241024.us-east-1.elb.amazonaws.com

; <<>> DiG 9.10.6 <<>> @185.213.26.187 internal-af90b8a66a8624061b5e32cc076dd867-1295241024.us-east-1.elb.amazonaws.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32969
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 4, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;internal-af90b8a66a8624061b5e32cc076dd867-1295241024.us-east-1.elb.amazonaws.com. IN A

;; AUTHORITY SECTION:
us-east-1.elb.amazonaws.com. 1462 IN	NS	ns-1119.awsdns-11.org.
us-east-1.elb.amazonaws.com. 1462 IN	NS	ns-1793.awsdns-32.co.uk.
us-east-1.elb.amazonaws.com. 1462 IN	NS	ns-235.awsdns-29.com.
us-east-1.elb.amazonaws.com. 1462 IN	NS	ns-934.awsdns-52.net.

;; Query time: 252 msec
;; SERVER: 185.213.26.187#53(185.213.26.187)
;; WHEN: Tue Aug 11 22:32:32 IST 2020
;; MSG SIZE  rcvd: 246

```

*DoH*

**Using CloudFlare**

```bash
$ curl -sSL -H 'accept: application/dns-json' 'https://cloudflare-dns.com/dns-query?name=internal-af90b8a66a8624061b5e32cc076dd867-1295241024.us-east-1.elb.amazonaws.com&type=A' | jq .
{
  "Status": 0,
  "TC": false,
  "RD": true,
  "RA": true,
  "AD": false,
  "CD": false,
  "Question": [
    {
      "name": "internal-af90b8a66a8624061b5e32cc076dd867-1295241024.us-east-1.elb.amazonaws.com",
      "type": 1
    }
  ],
  "Answer": [
    {
      "name": "internal-af90b8a66a8624061b5e32cc076dd867-1295241024.us-east-1.elb.amazonaws.com",
      "type": 1,
      "TTL": 60,
      "data": "10.1.28.204"
    }
  ]
}
```

**Using Pi-DNS**

```bash
$ curl -sSL -H 'accept: application/dns-json' 'https://doh.pi-dns.com/dns-query?name=internal-af90b8a66a8624061b5e32cc076dd867-1295241024.us-east-1.elb.amazonaws.com&type=A' | jq .
{
  "Status": 0,
  "TC": false,
  "RD": true,
  "RA": true,
  "AD": false,
  "CD": false,
  "Question": [
    {
      "name": "internal-af90b8a66a8624061b5e32cc076dd867-1295241024.us-east-1.elb.amazonaws.com.",
      "type": 1
    }
  ],
  "Authority": [
    {
      "name": "us-east-1.elb.amazonaws.com.",
      "type": 2,
      "TTL": 33,
      "Expires": "Tue, 11 Aug 2020 17:05:00 UTC",
      "data": "ns-1119.awsdns-11.org."
    },
    {
      "name": "us-east-1.elb.amazonaws.com.",
      "type": 2,
      "TTL": 33,
      "Expires": "Tue, 11 Aug 2020 17:05:00 UTC",
      "data": "ns-1793.awsdns-32.co.uk."
    },
    {
      "name": "us-east-1.elb.amazonaws.com.",
      "type": 2,
      "TTL": 33,
      "Expires": "Tue, 11 Aug 2020 17:05:00 UTC",
      "data": "ns-235.awsdns-29.com."
    },
    {
      "name": "us-east-1.elb.amazonaws.com.",
      "type": 2,
      "TTL": 33,
      "Expires": "Tue, 11 Aug 2020 17:05:00 UTC",
      "data": "ns-934.awsdns-52.net."
    }
  ],
  "edns_client_subnet": "61.2.213.0/0"
}
```

**Comment by NoExitTV** [comment]
Hi there.
Have had a lot to do lately so haven't had the time yet to organize all our configs and upload them to the repo.

In Unbound, we have the config:
```
# Ensure privacy of local IP ranges
private-address: 192.168.0.0/16
private-address: 169.254.0.0/16
private-address: 172.16.0.0/12
private-address: 10.0.0.0/8
private-address: fd00::/8
private-address: fe80::/10
```

According to the [Unbound documentation](https://www.nlnetlabs.nl/documentation/unbound/unbound.conf), they state:
> private-address: <IP address or subnet>
>               Give IPv4 of IPv6 addresses  or  classless  subnets.  These  are
>               addresses  on  your  private  network, and are not allowed to be
>               returned for public internet  names.   Any  occurrence  of  such
>               addresses are removed from DNS answers. Additionally, the DNSSEC
>               validator may mark the  answers  bogus.  This  protects  against
>               so-called  DNS  Rebinding, where a user browser is turned into a
>               network proxy, allowing remote access  through  the  browser  to
>               other  parts of your private network.  Some names can be allowed
>               to contain your private addresses, by default all the local-data
>               that  you  configured  is  allowed to, and you can specify addi-
>               tional names using private-domain.   No  private  addresses  are
>               enabled  by default.  We consider to enable this for the RFC1918
>               private IP address space by  default  in  later  releases.  That
>               would  enable  private  addresses  for  10.0.0.0/8 172.16.0.0/12
>               192.168.0.0/16 169.254.0.0/16 fd00::/8 and fe80::/10, since  the
>               RFC  standards  say these addresses should not be visible on the
>               public internet.  Turning on 127.0.0.0/8 would hinder many spam-
>               blocklists   as  they  use  that.   Adding  ::ffff:0:0/96  stops
>               IPv4-mapped IPv6 addresses from bypassing the filter.

That's the reason as to why the address 10.1.28.204 is removed from the answer when using pi-dns.
I'm not sure, is this a common thing for other DNS servers to have? Do we really increase the security by disabling lookup for local addresses?
Perhaps we should enable them? What do you think?

**Comment by frezbo** [comment]
@NoExitTV I looked up RFC1918 and it mentions blocking private address spaces, but it was written back in 1996, not sure about the update process. Since every other DNS provider seems to allow resolving public address space I don't see any harm in allowing lookup of local addresses. Also thanks for looking it up. 👍

**Comment by NoExitTV** [comment]
@frezbo Sorry for the late reply.
I've applied a new unbound config on all DNS servers now, allowing the response to include private addresses.

This issue should be fixed now! Let me know if you still have problems.
